"""Updated Pattern Field

Revision ID: 4bdf777ec514
Revises: bb5eb6aea6c7
Create Date: 2025-11-14 23:28:38.357524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bdf777ec514'
down_revision = 'bb5eb6aea6c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traffic_patterns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sample_size', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traffic_patterns', schema=None) as batch_op:
        batch_op.drop_column('sample_size')

    # ### end Alembic commands ###
