"""Add AI toggle fields

Revision ID: bb5eb6aea6c7
Revises: d2b9a73a5593
Create Date: 2025-11-13 07:47:03.370431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb5eb6aea6c7'
down_revision = 'd2b9a73a5593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traffic_light_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collection_mode', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ai_enabled_during_collection', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traffic_light_logs', schema=None) as batch_op:
        batch_op.drop_column('ai_enabled_during_collection')
        batch_op.drop_column('collection_mode')

    # ### end Alembic commands ###
