"""Add AI fields to TrafficPattern

Revision ID: d2b9a73a5593
Revises: cf8d8cd99a34
Create Date: 2025-11-10 05:30:16.118308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2b9a73a5593'
down_revision = 'cf8d8cd99a34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traffic_patterns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('best_action', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('action_success_rate', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traffic_patterns', schema=None) as batch_op:
        batch_op.drop_column('action_success_rate')
        batch_op.drop_column('best_action')

    # ### end Alembic commands ###
