"""2.0

Revision ID: e855d687b83b
Revises: 
Create Date: 2025-11-07 04:10:56.732220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e855d687b83b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('green_wave_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('green_wave_schedules', schema=None) as batch_op:
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###
